import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import HomeStyles from "../styles/home.module.css";
import { useRef, useState } from "react";
import Navbar from "../components/Navbar";
import MeetingDate from "../components/MeetingDate";
import Footer from "../components/Footer";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faInstagram, faLinkedin } from "@fortawesome/free-brands-svg-icons";
import { faEnvelope } from "@fortawesome/free-solid-svg-icons";

interface ResearchArea {
  name: string;
  image: string;
  shortDescription: string;
  detailedDescription: string;
}

const Home: NextPage = () => {
  const landingContainerRef = useRef<HTMLDivElement | null>(null);

  // State to track which areas are expanded (allow multiple expansions at once).
  const [expandedAreas, setExpandedAreas] = useState<string[]>([]);

  const researchAreas: ResearchArea[] = [
    {
      name: "Algorithmic Trading",
      image: "/algo.jpeg",
      shortDescription: "Teaching computers to trade better than humans.",
      detailedDescription:
        "In our Algorithmic Trading research area, we explore various strategies, implement machine learning models, and build automated trading systems that can outperform human decision making.",
    },
    {
      name: "Risk Management",
      image: "/risk.jpg",
      shortDescription: "Quantifying and managing risk in decision making.",
      detailedDescription:
        "Our Risk Management area focuses on identifying, quantifying, and mitigating risks. We study advanced statistical techniques and employ models that help in decision making under uncertainty.",
    },
    {
      name: "Data Science",
      image: "/ds.png",
      shortDescription: "Using data-driven models to solve real world problems.",
      detailedDescription:
        "The Data Science research area involves building and deploying predictive models, analyzing large datasets, and extracting actionable insights to solve complex, real-world problems.",
    },
  ];

  const toggleArea = (areaName: string) => {
    setExpandedAreas((prev) =>
      prev.includes(areaName)
        ? prev.filter((n) => n !== areaName)
        : [...prev, areaName]
    );
  };

  return (
    <>
      <Head>
        <title>McGill QR</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/mcgill_qr.ico" />
      </Head>

      {/* NAVBAR */}
      <Navbar />

      <main className="mx-auto flex min-h-screen overflow-hidden w-full flex-col items-center justify-center">
        {/* ========== HOME SECTION (#home) ========== */}
        <section
          id="home"
          ref={landingContainerRef}
          className="flex container p-5 relative justify-center lg:flex-row flex-col-reverse items-center w-full min-h-screen mb-20 md:mb-24"
        >
          <div className={`${HomeStyles.gradientBubbleOne}`}></div>
          <div className="flex-1 justify-center z-20 space-y-6 flex flex-col items-start w-full">
            <h1
              style={{ lineHeight: 1.1 }}
              className="md:text-8xl text-5xl font-medium text-white"
            >
              MCGILL QUANTITATIVE RESEARCH CLUB
            </h1>
            <h2 className="md:text-xl text-lg text-white font-light text-opacity-60">
              Providing students with practical quant research experience and
              meaningful industry exposure.
            </h2>

            <div className="space-x-6 flex">
              <a
                href="https://docs.google.com/forms/d/e/1FAIpQLSdxRC7RDKSa-dcPKMs0acPjmDk2Mastl6UnUKEBRxJnInd8qw/viewform?usp=sf_link"
                rel="noopener noreferrer nofollow"
                target="_blank"
              >
                <button className="bg-white transition-opacity hover:opacity-50 rounded-full px-8 py-3">
                  Join
                </button>
              </a>
            </div>
          </div>

          <div className="flex-1 flex mt-16 relative justify-center max-h-[1000px] items-center">
            <div className="lg:absolute lg:scale-150 z-10">
              {/* 
                UPDATED: Added 'rounded-xl' for softer corners.
                Use 'rounded-full' for a fully circular image.
              */}
              <Image
                src={"/sbcsclub/mcgill_qr.png"}
                quality={100}
                objectFit="contain"
                width={450}
                height={450}
                alt="logo"
                className="rounded-xl"
              />
            </div>
          </div>
        </section>

        {/* ========== ABOUT SECTION (#about) ========== */}
        <section
          id="about"
          className="min-h-[500px] pt-8 mb-[100px] items-center flex flex-col-reverse lg:flex-row max-w-7xl px-6 md:px-3"
        >
          <div className="flex-1 relative flex justify-center items-center px-10">
            {/* 
              UPDATED: Also add 'rounded-xl' so that trottier.jpg
              (or any image in this position) has softer corners.
            */}
            <Image
              src="/trottier.jpg"
              alt="Descriptive alt text"
              width={2000 / 3}
              height={1330 / 3}
              layout="intrinsic"
              className="object-contain rounded-xl"
            />
          </div>

          <div className="flex-1 my-[100px] lg:my-0 space-y-6">
            <h1
              style={{ lineHeight: 1.1 }}
              className="md:text-7xl text-5xl font-medium text-white"
            >
              <span className={`${HomeStyles.overviewHeader}`}></span>About Us
            </h1>
            <p className="md:text-xl text-lg text-white font-light text-opacity-60">
              <span className={HomeStyles.proHighlight}>
                McGill Quantitative Research
              </span>{" "}
              is a student-led initiative comprised of McGill’s brightest
              statistics, math, and computer science students.
            </p>

            <p className="md:text-xl text-lg text-white font-light text-opacity-60">
              Through mentorship and hands-on projects, we prepare members for
              successful careers in{" "}
              <span className={HomeStyles.proHighlight}>
                quantitative finance
              </span>
              , bridging the gap between academic theory and real-world
              application.
            </p>

            <p className="md:text-xl text-lg text-white font-light text-opacity-60">
              Our members collaborate on quant research projects, publish their
              findings, and connect with industry professionals. We are building
              a community where students advance their skills in{" "}
              <span className={HomeStyles.proHighlight}>
                algorithmic trading
              </span>
              , <span className={HomeStyles.proHighlight}>data science</span>,
              and <span className={HomeStyles.proHighlight}>risk management</span>.
            </p>
          </div>
        </section>

        {/* ========== WORKSHOPS (RESEARCH AREAS) SECTION ========== */}
        <section
          id="workshops"
          className="min-h-screen mt-6 flex-col space-y-6 flex max-w-7xl relative justify-center items-center"
        >
          <div className={`${HomeStyles.gradientBubbleTwo}`}></div>
          <h1
            style={{ lineHeight: 1.1 }}
            className="md:text-7xl text-5xl font-medium text-white uppercase"
          >
            Research Areas
          </h1>
          <h2 className="md:text-xl px-6 md:px-0 text-lg text-white font-light text-center text-opacity-60 mb-12">
            Our goal is to pursue exploratory projects and showcase our findings
            in these areas
          </h2>
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-x-8 gap-y-6 w-full items-start justify-items-center pt-[50px]">
            {researchAreas.map((area) => {
              const isExpanded = expandedAreas.includes(area.name);

              return (
                <div
                  key={area.name}
                  className="w-80 bg-black border border-white rounded-lg overflow-hidden cursor-pointer transform hover:scale-105 transition duration-300 text-center"
                  onClick={() => toggleArea(area.name)}
                >
                  <img
                    src={area.image}
                    alt={area.name}
                    className="w-full h-64 object-cover"
                  />
                  <div className="p-4">
                    <h3 className="text-xl font-bold uppercase text-white/80 mb-4">
                      {area.name}
                    </h3>
                    <p className="text-sm text-gray-400 uppercase">
                      {area.shortDescription}
                    </p>
                  </div>
                  {/* 
                    Always has a top border, but toggles color 
                    from transparent to white to animate simultaneously
                  */}
                  <div
                    className={`
                      overflow-hidden 
                      border-t 
                      transition-[max-height,border-color] 
                      duration-700 
                      ease-in-out
                      ${isExpanded ? "max-h-96 border-white" : "max-h-0 border-transparent"}
                    `}
                  >
                    <div className="p-4">
                      <p className="text-sm text-gray-300 leading-relaxed">
                        {area.detailedDescription}
                      </p>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </section>

        {/* ========== SOCIAL ICONS SECTION ========== */}
        <section className="min-h-[100px] my-0 flex-col space-y-3 flex max-w-7xl relative justify-center items-center">
          <div className="my-0 px-3 h-auto w-full relative flex space-x-6">
            {/* 
              UPDATED: increased the 'height' from 35 to 50 
              so they're visibly larger
            */}
            <a
              href="https://www.instagram.com/mcgill_qr/"
              target="_blank"
              rel="noopener noreferrer nofollow"
            >
              <FontAwesomeIcon icon={faInstagram} height={40} color="white" />
            </a>
            <a
              href="https://www.linkedin.com/company/mcgillqr/"
              target="_blank"
              rel="noopener noreferrer nofollow"
            >
              <FontAwesomeIcon icon={faLinkedin} height={40} color="white" />
            </a>
            <a
              href="mailto:info@mcgillqr.com"
              target="_blank"
              rel="noopener noreferrer nofollow"
            >
              <FontAwesomeIcon icon={faEnvelope} height={40} color="white" />
            </a>
          </div>
        </section>
      </main>

      <Footer />
    </>
  );
};

export default Home;
