name: Deploy to Server

on:
  workflow_dispatch:  # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server using SSH with password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          # Stop the process using port 3000
          fuser -k 3000/tcp || true
          
          # Navigate to the project directory
          cd /home/mcgillqr
          
          # Pull the latest code from master
          git pull origin master

          #install deps
          npm install
          
          # Rebuild the project
          npm run build
          
          # Start the project in the background
          nohup npm run start &> /dev/null &
